### PR TITLE
WIP: Token fixes

### PR DESCRIPTION
**Pull request by hackmod**
## WARNING
*Please do not merge it (WIP)*

## Description
support Token feature using the parity extension or geth.

## Done
- [x]  token: get abi from Contract DB.
   * use `async.waterfall()`
   * check `decimals()` is available
- [x] added a missing transferTokens directive, already used by the DaoController.
- [x] web3relay: setup `fromBlock` param
     * ~~show contract creation info. (FIXME) : temporal fix.~~ FIXED (8/3)
     * remove hardecoded fromBlock
     * ~~parse `req.body.fromBlock` for future use~~

- [x] token: show decimals
- [x] check tx_trace for ERC20 tokenContracts
  - [x] check ERC20 token validity (6/14)
- [x] fixed 'to' address for a contract. show txn.amount for a tokenContract.
- [x] enable parity extension locally. (`web3.trace.*`) (6/28)
- [x] save contract creation time both parity/geth (`tools/sync.js`) (7/22)
- [x] reduced transaction db size. (7/22)
~~- [ ] restrict `fromBlock` position in the `config.json`~~
- [x] check `decimals()` method optionally, (symbol, decimals are not part of ERC20/ERC233)
- [x] ~~`web3.trace.*` does not support pagination.~~ minimal support `web3.trace.*` pagination.
- [x] configurable `tokens.json`. remove ETC specific tokens from menu
- [x] show transfer transactions of all known tokens (8/3)
- [x] always decode transfer call transactions (8/3)
- [x] show created contract address (8/3)
- [x] minimal token support using geth (9/5)

## Todo
- [ ] fix possible bugs.

## Screenshot
etc-explorer + parity (using `web3.trace.*`)

### token transfer
image

### contract transactions
image

### contract source now working
image

### transaction view
image

### CODE REVIEW

**Comment by akx20000a** [comment]
**We need geth support primarily**

**Comment by hackmod** [comment]
without parity too much things to do. anyway I have a plan to support normal geth as well, already done but partially by the etherzero project.

**Comment by hackmod** [comment]
- [x] save contract creation time both parity/geth (`tools/sync.js`)
- [x] reduced transaction db size.

**Comment by hackmod** [comment]
## Screen shots

image

- correct receiver (decoded) address, decoded amount of tokens
image

- always decode transfer transactions, transaction pagination.
image

- simplified menu (remove ETC specific tokens, extact "`tokens.json`" as a configurable option)
- enable `verify contract` menu
image

**Comment by hackmod** [comment]
before
image

after
image

**Comment by hackmod** [comment]
almost done 😃 
minimal change has been applied using parity extension `trace.filter`
- check speed issue.
- fix any possible bugs.

**Comment by eosclassicteam** [comment]
Looks good to me, however we should hide "Known ERC20 token transactions" menu when there is no transaction for account.

**Comment by eosclassicteam** [comment]
Yup, there is an error viewing contract source 

```
ubuntu@ip-172-31-22-53:~/eosc-explorer$ node app.js
CONFIG FOUND: Node:localhost | Port:8282
Web3 connection established
(node:11908) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/4.x/docs/connections.html#use-mongo-client
Express server listening on port 3000
GET /addr/0xf33f40d9c8b380eb5b01e20df0cb4cbde3341626 200 9.846 ms - 6953
GET /config 304 1.942 ms - -
GET /tpl/page-head.html 304 1.623 ms - -
GET /tpl/footer.html 304 0.357 ms - -
GET /tpl/header.html 304 0.288 ms - -
GET /views/address.html 304 0.310 ms - -
GET /views/contract-source.html 304 0.314 ms - -
{ addr: '0xf33f40d9c8b380eb5b01e20df0cb4cbde3341626',
  options: [ 'balance', 'count', 'bytecode' ] }
POST /web3relay 200 519.473 ms - -
{ addr: '0xf33f40d9c8b380eb5b01e20df0cb4cbde3341626',
  action: 'find' }
(node:11908) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
POST /compile 200 9.831 ms - -
POST /addr 200 5.033 ms - -
{ addr_trace: '0xf33f40d9c8b380eb5b01e20df0cb4cbde3341626' }
POST /addr_count 200 134.863 ms - -
/home/ubuntu/eosc-explorer/node_modules/solc/soljson.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileSync"](filename);if(!

TypeError: Cannot read property 'filter' of undefined
    at /home/ubuntu/eosc-explorer/routes/web3relay.js:352:18
    at /home/ubuntu/eosc-explorer/node_modules/async/dist/async.js:473:16
    at next (/home/ubuntu/eosc-explorer/node_modules/async/dist/async.js:5315:29)
    at /home/ubuntu/eosc-explorer/node_modules/async/dist/async.js:958:16
    at /home/ubuntu/eosc-explorer/routes/web3relay.js:318:11
    at nextTask (/home/ubuntu/eosc-explorer/node_modules/async/dist/async.js:5310:14)
    at next (/home/ubuntu/eosc-explorer/node_modules/async/dist/async.js:5317:9)
    at /home/ubuntu/eosc-explorer/node_modules/async/dist/async.js:958:16
    at /home/ubuntu/eosc-explorer/routes/web3relay.js:301:13
    at nextTask (/home/ubuntu/eosc-explorer/node_modules/async/dist/async.js:5310:14)
    at next (/home/ubuntu/eosc-explorer/node_modules/async/dist/async.js:5317:9)
    at /home/ubuntu/eosc-explorer/node_modules/async/dist/async.js:958:16
    at /home/ubuntu/eosc-explorer/routes/web3relay.js:274:11
    at /home/ubuntu/eosc-explorer/node_modules/mongoose/lib/query.js:3118:18
    at newTickHandler (/home/ubuntu/eosc-explorer/node_modules/mpromise/lib/promise.js:234:18)
```

Explorer crashes during contract source verification

**Comment by hackmod** [comment]
## screenshot

make consistent pagination

image

**Comment by hackmod** [comment]
minimal geth support added. (multi-geth or ethereum-geth)

**Comment by hackmod** [comment]
@pyskell 
currently, we are going to prepare ETC node, to test real situation, find any possible bugs

Please feel free to feedback any suggestion :)

**Comment by hackmod** [comment]
etc-explorer on the ETC chain :)
image

**Comment by naikmyeong** [comment]
See https://github.com/ethereumclassic/explorer/commit/001d582b8a52eebb8c94d5d6d6920d20f1bc3bdd

**Comment by naikmyeong** [comment]
CPU usage high when loading token page

**Comment by btenterprise2020** [comment]
Rebase your PR!

**Comment by benjioh5** [comment]
Still on WIP?

**Comment by hackmod** [comment]
> Still on WIP?

this is outdated (web3 1.x based).

some parts had been already merged by another PR and some parts remained experimental.

**Pull request closed without merging**
