### PR TITLE
BACKMERGE: Dev -> master

### PR DESCRIPTION
**Pull request by phyro**
syncing master with changes to dev

### CODE REVIEW

**Comment by kimisan** [comment]
@btenterprise2020 
blockchain height 7,886,455 and 7886447 are at different.
Blocks 7886447 is not synced, why ?
My setting,
```
"nodeAddr":     "localhost",
    "wsPort":       8546,
    "startBlock":   7886439,
    "endBlock":     "latest",
    "quiet":        true,
    "syncAll":      true,
```

螢幕快照 2019-04-20 下午9 16 40

**Comment by kimisan** [comment]
@phyro ,just check out the DEV branch, does your "accounts" page can working?

**Comment by kimisan** [comment]
@hackmod Sorry, may you have some time to check dev branch.

**Comment by hackmod** [comment]
accounts page have a small regression bug after gulpfiled.

**Comment by phyro** [comment]
closing this one as there is not movement and the guy making the changes was very suspicious

**Comment by kimisan** [comment]
yap.

**Pull request closed without merging**
