### PR TITLE
fixed broken web3relay

### PR DESCRIPTION
**Pull request by hackmod**
fixed regression by commit c54a642a77bca

- [x] search block hash correctly after fail to search tx hash.
- [x] show tx info correctly with no tx DB cases.
- [x] check web3 2.0.0 + web3explorer compatibility (fixed at #328)

### CODE REVIEW

**Comment by streetcrypto7** [comment]
@hackmod I think this PR can be closed?

**Comment by kimisan** [comment]
@hackmod should close this PR?

**Comment by streetcrypto7** [comment]
@kimisan I see that commits are already merged here https://github.com/ethereumclassic/explorer/pull/327

**Comment by hackmod** [comment]
oops! this PR accidentally merged at #327 
(this PR is separable and another small issue not related with the latest web3)

**Comment by kimisan** [comment]
> oops! this PR accidentally merged at #327
> (this PR is separable and another small issue not related with the latest web3)

got it. so may i close it ?

**Pull request closed without merging**
